version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout
      - run:
          name: Install python project dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Testing with pytest
          command: pytest
      - run:
          name: Testing linting with flake8
          command: flake8 --exclude env,migrations

workflows:
  build-and-test:
    jobs:
      - test
