version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout
      - run:
          name: Testing with pytest
          command: |
            pip3 install -r requirements.txt
            pytest
      - run:
          name: Testing linting with flake8
          command: |
            pip3 install -r requirements.txt
            flake8 --exclude env,migrations
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/push-docker-image
workflows:
  build-and-test:
    jobs:
      - test
      - deploy:
          requires:
            - test
