version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout
      - run:
          name: Testing with pytest
          command: |
            pip3 install -r requirements.txt
            pytest
      - run:
          name: Testing linting with flake8
          command: |
            pip3 install -r requirements.txt
            flake8 --exclude env,migrations
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a oc-lettings-9 web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a oc-lettings-9 web

workflows:
  build-and-test:
    jobs:
      - test
      - deploy:
          requires:
            - test
