version: 2.1

jobs:
  # Job 1 : tests (unit tests & linting)
  test:
    docker:
      - image: cimg/python:3.9.8
    steps:
      - checkout
      - run:
          name: Testing with pytest
          command: |
            pip3 install -r requirements.txt
            pytest
      - run:
          name: Testing linting with flake8
          command: |
            pip3 install -r requirements.txt
            flake8 --exclude env,migrations

  #Job 2 : Build the Docker image and push it to Docker hub
  containerize:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          TAG=$CIRCLE_SHA1
          docker build -t virgindocker75/oc-lettings:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push virgindocker75/oc-lettings:$TAG

  # Job 3 : Deploy the docker image to Heroku
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push Docker image to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a oc-lettings-9 web
            HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a oc-lettings-9 web

workflows:
  build-and-test:
    jobs:
      - test
      - containerize
      - deploy:
          requires:
            - test
            - containerize
