# Generated by Django 3.0 on 2021-11-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0003_auto_20211124_2109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
